apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ include "cnpg-mcp.fullname" . }}-oidc-config
  labels:
    {{- include "cnpg-mcp.labels" . | nindent 4 }}
data:
  # REQUIRED: OIDC Issuer URL
  OIDC_ISSUER: {{ .Values.oidc.issuer | quote }}

  # REQUIRED: Expected audience claim in JWT tokens
  OIDC_AUDIENCE: {{ .Values.oidc.audience | quote }}

  {{- if .Values.oidc.jwksUri }}
  # OPTIONAL: Override JWKS URI
  OIDC_JWKS_URI: {{ .Values.oidc.jwksUri | quote }}
  {{- end }}

  {{- if .Values.oidc.dcrProxyUrl }}
  # OPTIONAL: DCR proxy URL
  DCR_PROXY_URL: {{ .Values.oidc.dcrProxyUrl | quote }}
  {{- end }}

  {{- if .Values.oidc.scope }}
  # OPTIONAL: Required OAuth2 scope
  OIDC_SCOPE: {{ .Values.oidc.scope | quote }}
  {{- end }}
