---
# Service Account for the MCP server
apiVersion: v1
kind: ServiceAccount
metadata:
  name: cnpg-mcp-server
  namespace: default

---
# ClusterRoleBinding to use CloudNativePG's built-in edit role
# The CloudNativePG helm chart creates these roles automatically:
#   - cnpg-cloudnative-pg (full admin)
#   - cnpg-cloudnative-pg-edit (edit access)
#   - cnpg-cloudnative-pg-view (read-only)
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRoleBinding
metadata:
  name: cnpg-mcp-server-binding
subjects:
  - kind: ServiceAccount
    name: cnpg-mcp-server
    namespace: default
roleRef:
  kind: ClusterRole
  name: cnpg-cloudnative-pg-edit  # Use edit role for full MCP capabilities
  apiGroup: rbac.authorization.k8s.io

---
# Additional ClusterRoleBinding for viewing pods/logs/events
# The cnpg roles only cover postgresql.cnpg.io resources,
# so we need additional permissions for core resources
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRoleBinding
metadata:
  name: cnpg-mcp-server-view-binding
subjects:
  - kind: ServiceAccount
    name: cnpg-mcp-server
    namespace: default
roleRef:
  kind: ClusterRole
  name: view  # Built-in Kubernetes view role for pods, events, etc.
  apiGroup: rbac.authorization.k8s.io
